/// Valid example values used to pre-fill the form on first load, so the
/// user doesn't have to manually type all 38 fields before they can try
/// the app -- they can hit Predict immediately, or just edit the handful
/// of fields they actually want to experiment with. These are the same
/// example values documented in the FastAPI service's schemas.py.
const Map<String, String> kFieldDefaults = {
  'protocol_type': 'tcp',
  'service': 'http',
  'flag': 'SF',
  'duration': '0',
  'src_bytes': '232',
  'dst_bytes': '8153',
  'land': '0',
  'wrong_fragment': '0',
  'urgent': '0',
  'hot': '0',
  'num_failed_logins': '0',
  'logged_in': '1',
  'num_compromised': '0',
  'root_shell': '0',
  'su_attempted': '0',
  'num_root': '0',
  'num_file_creations': '0',
  'num_shells': '0',
  'num_access_files': '0',
  'is_guest_login': '0',
  'srv_count': '5',
  'serror_rate': '0.0',
  'srv_serror_rate': '0.0',
  'rerror_rate': '0.0',
  'srv_rerror_rate': '0.0',
  'same_srv_rate': '1.0',
  'diff_srv_rate': '0.0',
  'srv_diff_host_rate': '0.0',
  'dst_host_count': '30',
  'dst_host_srv_count': '255',
  'dst_host_same_srv_rate': '1.0',
  'dst_host_diff_srv_rate': '0.0',
  'dst_host_same_src_port_rate': '0.03',
  'dst_host_srv_diff_host_rate': '0.04',
  'dst_host_serror_rate': '0.03',
  'dst_host_srv_serror_rate': '0.01',
  'dst_host_rerror_rate': '0.0',
  'dst_host_srv_rerror_rate': '0.01',
};
